# Generated by Django 6.0.6 on 2026-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='Python', max_length=20),
        ),
    ]
